#pragma once
#include "structs.h"

void shuffleDeck(tile* deck, int size);

tile draw(tile* deck, int size);

void shiftLeft(tile* deck, int size);
/* CETTE FONCTION DÉCALE TOUTES LES TUILES VERS LA GAUCHE DU PAQUET, CETTE FONCTION
SERVIRA A DEUX CHOSES, PREMIEREMENT, LORSQUE L'ON PIOCHE UNE CARTE QUE L'ON NE PEUT PAS 
JOUER, ON DECALE LES ELEMENTS ET ON REESSAYE AVEC LA CARTE SUIVANTE.
SECONDEMENT, SI ON A EFFECTUÉ TAILLE DÉCALAGES, CELA SIGNIFIE QU'AUCUNE TUILE N'EST
JOUABLE ET DONC LE JEU S'ARRÊTE. */